/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lemuel
 */
public class MoreCoffeeScroll extends javax.swing.JFrame {

    /**
     * Creates new form MoreCoffeeScroll
     */
    public MoreCoffeeScroll() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel1 = new java.awt.Panel();
        coffeepanel4 = new javax.swing.JPanel();
        coffeepanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        image1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        coffeeNames4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        ratings1 = new javax.swing.JLabel();
        seemore4 = new javax.swing.JButton();
        addtocart1 = new javax.swing.JButton();
        coffeepanel5 = new javax.swing.JPanel();
        coffeepanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        image2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        coffeeNames5 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        ratings2 = new javax.swing.JLabel();
        seemorebtn5 = new javax.swing.JButton();
        addtocart2 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        coffeepanel3 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        image3 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        coffeeNames3 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        ratings3 = new javax.swing.JLabel();
        Sbseemorebtn6 = new javax.swing.JButton();
        addtocart3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        coffeepanel7 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        image5 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        coffeeNames1 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        SbSeemore1 = new javax.swing.JButton();
        addtocart4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        coffeepanel8 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        image6 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        coffeeNames2 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        SbSeemore2 = new javax.swing.JButton();
        addtocart5 = new javax.swing.JButton();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        coffeepanel9 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        image7 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        coffeeNames7 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        SbSeemore3 = new javax.swing.JButton();
        addtocart6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        coffeepanel10 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        image8 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        coffeeNames8 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        SbSeemore4 = new javax.swing.JButton();
        addtocart7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        coffeepanel11 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        image9 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        coffeeNames9 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        SbSeemore5 = new javax.swing.JButton();
        addtocart8 = new javax.swing.JButton();
        jPanel45 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        coffeepanel12 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        image10 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        coffeeNames10 = new javax.swing.JLabel();
        jPanel50 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        SbSeemore6 = new javax.swing.JButton();
        addtocart9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1301, 10234));

        panel1.setBackground(new java.awt.Color(102, 51, 0));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        coffeepanel1.setBackground(new java.awt.Color(204, 204, 204));
        coffeepanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setPreferredSize(new java.awt.Dimension(270, 270));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(153, 153, 153,80));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Php 190.00");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 110, 40));

        image1.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\Downloads\\nitrocoldbrew.png")); // NOI18N
        jPanel6.add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 190, 252));

        coffeepanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 270, 250));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        coffeeNames4.setBackground(new java.awt.Color(255, 255, 255, 80));
        coffeeNames4.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        coffeeNames4.setText("Nitro Cold Brew");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(coffeeNames4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(coffeeNames4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        coffeepanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 300, 50));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        ratings1.setBackground(new java.awt.Color(204, 204, 204));
        ratings1.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\OneDrive\\Pictures\\4.5ratefinal.png")); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(ratings1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(ratings1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        coffeepanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 330, -1, 60));

        seemore4.setBackground(new java.awt.Color(204, 204, 204));
        seemore4.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        seemore4.setText("See more...");
        seemore4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        seemore4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seemore4ActionPerformed(evt);
            }
        });
        coffeepanel1.add(seemore4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 90, 30));

        addtocart1.setBackground(new java.awt.Color(204, 204, 204));
        addtocart1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        addtocart1.setText("Add to Cart");
        addtocart1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        addtocart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocart1ActionPerformed(evt);
            }
        });
        coffeepanel1.add(addtocart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 90, 30));

        javax.swing.GroupLayout coffeepanel4Layout = new javax.swing.GroupLayout(coffeepanel4);
        coffeepanel4.setLayout(coffeepanel4Layout);
        coffeepanel4Layout.setHorizontalGroup(
            coffeepanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coffeepanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        coffeepanel4Layout.setVerticalGroup(
            coffeepanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coffeepanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(coffeepanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel1.add(coffeepanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 350, 460));

        coffeepanel2.setBackground(new java.awt.Color(204, 204, 204));
        coffeepanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setPreferredSize(new java.awt.Dimension(270, 270));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Php 280.00");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 120, 40));

        image2.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\Downloads\\irishcreamcoldbrew.png")); // NOI18N
        jPanel9.add(image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 252));

        coffeepanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 270, 250));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));

        coffeeNames5.setBackground(new java.awt.Color(255, 255, 255, 80));
        coffeeNames5.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        coffeeNames5.setText("Irish Cream Cold Brew");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(coffeeNames5, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(coffeeNames5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        coffeepanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 270, 50));

        jPanel11.setBackground(new java.awt.Color(204, 204, 204));

        ratings2.setBackground(new java.awt.Color(204, 204, 204));
        ratings2.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\OneDrive\\Pictures\\3.5ratefinal.png")); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(ratings2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(ratings2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        coffeepanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 330, -1, 60));

        seemorebtn5.setBackground(new java.awt.Color(204, 204, 204));
        seemorebtn5.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        seemorebtn5.setText("See more...");
        seemorebtn5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        seemorebtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seemorebtn5ActionPerformed(evt);
            }
        });
        coffeepanel2.add(seemorebtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 90, 30));

        addtocart2.setBackground(new java.awt.Color(204, 204, 204));
        addtocart2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        addtocart2.setText("Add to Cart");
        addtocart2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        addtocart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocart2ActionPerformed(evt);
            }
        });
        coffeepanel2.add(addtocart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 90, 30));

        javax.swing.GroupLayout coffeepanel5Layout = new javax.swing.GroupLayout(coffeepanel5);
        coffeepanel5.setLayout(coffeepanel5Layout);
        coffeepanel5Layout.setHorizontalGroup(
            coffeepanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coffeepanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        coffeepanel5Layout.setVerticalGroup(
            coffeepanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, coffeepanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(coffeepanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel1.add(coffeepanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 350, 460));

        coffeepanel3.setBackground(new java.awt.Color(204, 204, 204));
        coffeepanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(204, 204, 204));
        jPanel18.setPreferredSize(new java.awt.Dimension(270, 270));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel19.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Php 205.00");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 120, 40));

        image3.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\Downloads\\CaramelMacchiato.png")); // NOI18N
        jPanel18.add(image3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 252));

        coffeepanel3.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 270, 250));

        jPanel20.setBackground(new java.awt.Color(204, 204, 204));

        coffeeNames3.setBackground(new java.awt.Color(255, 255, 255, 80));
        coffeeNames3.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        coffeeNames3.setText("Caramel Macchiato");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(coffeeNames3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(coffeeNames3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        coffeepanel3.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 270, 50));

        jPanel21.setBackground(new java.awt.Color(204, 204, 204));

        ratings3.setBackground(new java.awt.Color(204, 204, 204));
        ratings3.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\OneDrive\\Pictures\\5.0.png")); // NOI18N

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addComponent(ratings3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(ratings3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        coffeepanel3.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 330, -1, 60));

        Sbseemorebtn6.setBackground(new java.awt.Color(204, 204, 204));
        Sbseemorebtn6.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        Sbseemorebtn6.setText("See more...");
        Sbseemorebtn6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        Sbseemorebtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sbseemorebtn6ActionPerformed(evt);
            }
        });
        coffeepanel3.add(Sbseemorebtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 90, 30));

        addtocart3.setBackground(new java.awt.Color(204, 204, 204));
        addtocart3.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        addtocart3.setText("Add to Cart");
        addtocart3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        addtocart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocart3ActionPerformed(evt);
            }
        });
        coffeepanel3.add(addtocart3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 90, 30));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coffeepanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(coffeepanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 90, 350, 460));

        coffeepanel7.setBackground(new java.awt.Color(204, 204, 204));
        coffeepanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(204, 204, 204));
        jPanel15.setPreferredSize(new java.awt.Dimension(270, 270));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Php 39.00");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 120, 40));

        image5.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\Downloads\\IcedCaramelMacchiato.png")); // NOI18N
        jPanel15.add(image5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 252));

        coffeepanel7.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 270, 250));

        jPanel22.setBackground(new java.awt.Color(204, 204, 204));

        coffeeNames1.setBackground(new java.awt.Color(255, 255, 255, 80));
        coffeeNames1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        coffeeNames1.setText("Iced Caramel Macchiato");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(coffeeNames1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addComponent(coffeeNames1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        coffeepanel7.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 330, 50));

        jPanel23.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\OneDrive\\Pictures\\3.5ratefinal.png")); // NOI18N

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 101, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        coffeepanel7.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 330, 50));

        SbSeemore1.setBackground(new java.awt.Color(204, 204, 204));
        SbSeemore1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        SbSeemore1.setText("See more...");
        SbSeemore1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        SbSeemore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbSeemore1ActionPerformed(evt);
            }
        });
        coffeepanel7.add(SbSeemore1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 90, 30));

        addtocart4.setBackground(new java.awt.Color(204, 204, 204));
        addtocart4.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        addtocart4.setText("Add to Cart");
        addtocart4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        addtocart4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocart4ActionPerformed(evt);
            }
        });
        coffeepanel7.add(addtocart4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 90, 30));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(coffeepanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coffeepanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 350, 460));

        coffeepanel8.setBackground(new java.awt.Color(204, 204, 204));
        coffeepanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setBackground(new java.awt.Color(204, 204, 204));
        jPanel24.setPreferredSize(new java.awt.Dimension(270, 270));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel25.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Php 39.00");

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel24.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 120, 40));

        image6.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\Downloads\\DonDarko.png")); // NOI18N
        jPanel24.add(image6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 252));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        jPanel24.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(-46, -30, 360, -1));

        coffeepanel8.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 270, 250));

        jPanel27.setBackground(new java.awt.Color(204, 204, 204));

        coffeeNames2.setBackground(new java.awt.Color(255, 255, 255, 80));
        coffeeNames2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        coffeeNames2.setText("Don Darko");

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(coffeeNames2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addComponent(coffeeNames2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        coffeepanel8.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 330, 50));

        jPanel28.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\OneDrive\\Pictures\\5.0.png")); // NOI18N

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 101, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        coffeepanel8.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 330, 50));

        SbSeemore2.setBackground(new java.awt.Color(204, 204, 204));
        SbSeemore2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        SbSeemore2.setText("See more...");
        SbSeemore2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        SbSeemore2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbSeemore2ActionPerformed(evt);
            }
        });
        coffeepanel8.add(SbSeemore2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 90, 30));

        addtocart5.setBackground(new java.awt.Color(204, 204, 204));
        addtocart5.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        addtocart5.setText("Add to Cart");
        addtocart5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        addtocart5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocart5ActionPerformed(evt);
            }
        });
        coffeepanel8.add(addtocart5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 90, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(coffeepanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(coffeepanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, 350, 460));

        coffeepanel9.setBackground(new java.awt.Color(204, 204, 204));
        coffeepanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel31.setBackground(new java.awt.Color(204, 204, 204));
        jPanel31.setPreferredSize(new java.awt.Dimension(270, 270));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel32.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Php 39.00");

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel31.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 120, 40));

        image7.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\Downloads\\DonyaStrawberry.png")); // NOI18N
        jPanel31.add(image7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 252));

        coffeepanel9.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 270, 250));

        jPanel33.setBackground(new java.awt.Color(204, 204, 204));

        coffeeNames7.setBackground(new java.awt.Color(255, 255, 255, 80));
        coffeeNames7.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        coffeeNames7.setText("Donya Strawberry");

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(coffeeNames7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addComponent(coffeeNames7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        coffeepanel9.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 330, 50));

        jPanel34.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\OneDrive\\Pictures\\5.0.png")); // NOI18N

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 101, Short.MAX_VALUE))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        coffeepanel9.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 330, 50));

        SbSeemore3.setBackground(new java.awt.Color(204, 204, 204));
        SbSeemore3.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        SbSeemore3.setText("See more...");
        SbSeemore3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        SbSeemore3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbSeemore3ActionPerformed(evt);
            }
        });
        coffeepanel9.add(SbSeemore3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 90, 30));

        addtocart6.setBackground(new java.awt.Color(204, 204, 204));
        addtocart6.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        addtocart6.setText("Add to Cart");
        addtocart6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        addtocart6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocart6ActionPerformed(evt);
            }
        });
        coffeepanel9.add(addtocart6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 90, 30));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel30Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(coffeepanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coffeepanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel29Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel29Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel1.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 610, 350, 460));

        coffeepanel10.setBackground(new java.awt.Color(204, 204, 204));
        coffeepanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel36.setBackground(new java.awt.Color(204, 204, 204));
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel37.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel11.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Php 39.00");

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel36.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 120, 40));

        image8.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\Downloads\\BlackForest.png")); // NOI18N
        jPanel36.add(image8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 270));

        coffeepanel10.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 270, 250));

        jPanel38.setBackground(new java.awt.Color(204, 204, 204));

        coffeeNames8.setBackground(new java.awt.Color(255, 255, 255, 80));
        coffeeNames8.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        coffeeNames8.setText("Black Forest");

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(coffeeNames8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addComponent(coffeeNames8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        coffeepanel10.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 330, 50));

        jPanel39.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\OneDrive\\Pictures\\5.0.png")); // NOI18N

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 101, Short.MAX_VALUE))
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        coffeepanel10.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 330, 50));

        SbSeemore4.setBackground(new java.awt.Color(204, 204, 204));
        SbSeemore4.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        SbSeemore4.setText("See more...");
        SbSeemore4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        SbSeemore4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbSeemore4ActionPerformed(evt);
            }
        });
        coffeepanel10.add(SbSeemore4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 90, 30));

        addtocart7.setBackground(new java.awt.Color(204, 204, 204));
        addtocart7.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        addtocart7.setText("Add to Cart");
        addtocart7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        addtocart7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocart7ActionPerformed(evt);
            }
        });
        coffeepanel10.add(addtocart7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 90, 30));

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel35Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(coffeepanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coffeepanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 1130, 350, 460));

        coffeepanel11.setBackground(new java.awt.Color(204, 204, 204));
        coffeepanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel41.setBackground(new java.awt.Color(204, 204, 204));
        jPanel41.setPreferredSize(new java.awt.Dimension(270, 270));
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel42.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Php 39.00");

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel41.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 120, 40));

        image9.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\Downloads\\classicAmericano.png")); // NOI18N
        jPanel41.add(image9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 252));

        coffeepanel11.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 270, 250));

        jPanel43.setBackground(new java.awt.Color(204, 204, 204));

        coffeeNames9.setBackground(new java.awt.Color(255, 255, 255, 80));
        coffeeNames9.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        coffeeNames9.setText("Classic Americano");

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(coffeeNames9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addComponent(coffeeNames9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        coffeepanel11.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 330, 50));

        jPanel44.setBackground(new java.awt.Color(204, 204, 204));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\OneDrive\\Pictures\\4.5rate.png")); // NOI18N

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 101, Short.MAX_VALUE))
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        coffeepanel11.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 330, 50));

        SbSeemore5.setBackground(new java.awt.Color(204, 204, 204));
        SbSeemore5.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        SbSeemore5.setText("See more...");
        SbSeemore5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        SbSeemore5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbSeemore5ActionPerformed(evt);
            }
        });
        coffeepanel11.add(SbSeemore5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 90, 30));

        addtocart8.setBackground(new java.awt.Color(204, 204, 204));
        addtocart8.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        addtocart8.setText("Add to Cart");
        addtocart8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        addtocart8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocart8ActionPerformed(evt);
            }
        });
        coffeepanel11.add(addtocart8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 90, 30));

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel40Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(coffeepanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coffeepanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 1130, 350, 460));

        coffeepanel12.setBackground(new java.awt.Color(204, 204, 204));
        coffeepanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel47.setBackground(new java.awt.Color(204, 204, 204));
        jPanel47.setPreferredSize(new java.awt.Dimension(270, 270));
        jPanel47.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel48.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel15.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Php 39.00");

        javax.swing.GroupLayout jPanel48Layout = new javax.swing.GroupLayout(jPanel48);
        jPanel48.setLayout(jPanel48Layout);
        jPanel48Layout.setHorizontalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel48Layout.setVerticalGroup(
            jPanel48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel47.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 120, 40));

        image10.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\Downloads\\HazelnutMacchiato.png")); // NOI18N
        jPanel47.add(image10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 252));

        coffeepanel12.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 270, 250));

        jPanel49.setBackground(new java.awt.Color(204, 204, 204));

        coffeeNames10.setBackground(new java.awt.Color(255, 255, 255, 80));
        coffeeNames10.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        coffeeNames10.setText("Hazelnut Macchiato");

        javax.swing.GroupLayout jPanel49Layout = new javax.swing.GroupLayout(jPanel49);
        jPanel49.setLayout(jPanel49Layout);
        jPanel49Layout.setHorizontalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel49Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(coffeeNames10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );
        jPanel49Layout.setVerticalGroup(
            jPanel49Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel49Layout.createSequentialGroup()
                .addComponent(coffeeNames10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        coffeepanel12.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 330, 50));

        jPanel50.setBackground(new java.awt.Color(204, 204, 204));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\lemuel\\OneDrive\\Pictures\\5.0.png")); // NOI18N

        javax.swing.GroupLayout jPanel50Layout = new javax.swing.GroupLayout(jPanel50);
        jPanel50.setLayout(jPanel50Layout);
        jPanel50Layout.setHorizontalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel50Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 101, Short.MAX_VALUE))
        );
        jPanel50Layout.setVerticalGroup(
            jPanel50Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel50Layout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        coffeepanel12.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 330, 50));

        SbSeemore6.setBackground(new java.awt.Color(204, 204, 204));
        SbSeemore6.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        SbSeemore6.setText("See more...");
        SbSeemore6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        SbSeemore6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbSeemore6ActionPerformed(evt);
            }
        });
        coffeepanel12.add(SbSeemore6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 90, 30));

        addtocart9.setBackground(new java.awt.Color(204, 204, 204));
        addtocart9.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        addtocart9.setText("Add to Cart");
        addtocart9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        addtocart9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocart9ActionPerformed(evt);
            }
        });
        coffeepanel12.add(addtocart9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 90, 30));

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel46Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(coffeepanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(coffeepanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel45Layout = new javax.swing.GroupLayout(jPanel45);
        jPanel45.setLayout(jPanel45Layout);
        jPanel45Layout.setHorizontalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel45Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel45Layout.setVerticalGroup(
            jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(jPanel45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel45Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel1.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 1130, 350, 460));

        jScrollPane1.setViewportView(panel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 190, 200));

        setSize(new java.awt.Dimension(1317, 10242));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addtocart9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocart9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtocart9ActionPerformed

    private void SbSeemore6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbSeemore6ActionPerformed
        DonMacSeemore6 see = new DonMacSeemore6();
        see.setLocationRelativeTo(this); // Center the new window relative to DiscoverPage
        see.setVisible(true);
    }//GEN-LAST:event_SbSeemore6ActionPerformed

    private void addtocart8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocart8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtocart8ActionPerformed

    private void SbSeemore5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbSeemore5ActionPerformed
        DonMacSeemore5 see = new DonMacSeemore5();
        see.setLocationRelativeTo(this); // Center the new window relative to DiscoverPage
        see.setVisible(true);
    }//GEN-LAST:event_SbSeemore5ActionPerformed

    private void addtocart7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocart7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtocart7ActionPerformed

    private void SbSeemore4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbSeemore4ActionPerformed
        DonMacSeemore4 see = new  DonMacSeemore4();
        see.setLocationRelativeTo(this); // Center the new window relative to DiscoverPage
        see.setVisible(true);
    }//GEN-LAST:event_SbSeemore4ActionPerformed

    private void addtocart6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocart6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtocart6ActionPerformed

    private void SbSeemore3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbSeemore3ActionPerformed
        DonMacSeemore3 see = new DonMacSeemore3();
        see.setLocationRelativeTo(this); // Center the new window relative to DiscoverPage
        see.setVisible(true);
    }//GEN-LAST:event_SbSeemore3ActionPerformed

    private void addtocart5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocart5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtocart5ActionPerformed

    private void SbSeemore2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbSeemore2ActionPerformed
        DonMacSeemore2 see = new DonMacSeemore2();
        see.setLocationRelativeTo(this); // Center the new window relative to DiscoverPage
        see.setVisible(true);
    }//GEN-LAST:event_SbSeemore2ActionPerformed

    private void addtocart4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocart4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtocart4ActionPerformed

    private void SbSeemore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbSeemore1ActionPerformed
        DonMacSeemore1 see = new DonMacSeemore1();
        see.setLocationRelativeTo(this); // Center the new window relative to DiscoverPage
        see.setVisible(true);
    }//GEN-LAST:event_SbSeemore1ActionPerformed

    private void addtocart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocart3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtocart3ActionPerformed

    private void Sbseemorebtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sbseemorebtn6ActionPerformed
        SbSeemore6 more = new SbSeemore6();
        more.setLocationRelativeTo(this); // Center the new window relative to DiscoverPage
        more.setVisible(true);
    }//GEN-LAST:event_Sbseemorebtn6ActionPerformed

    private void addtocart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocart2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtocart2ActionPerformed

    private void seemorebtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seemorebtn5ActionPerformed
        Seemore5 more = new Seemore5();
        more.setLocationRelativeTo(this); // Center the new window relative to DiscoverPage
        more.setVisible(true);
    }//GEN-LAST:event_seemorebtn5ActionPerformed

    private void addtocart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocart1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addtocart1ActionPerformed

    private void seemore4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seemore4ActionPerformed
        Seemore4 more = new Seemore4();
        more.setLocationRelativeTo(this); // Center the new window relative to DiscoverPage
        more.setVisible(true);
    }//GEN-LAST:event_seemore4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoreCoffeeScroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoreCoffeeScroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoreCoffeeScroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoreCoffeeScroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoreCoffeeScroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SbSeemore1;
    private javax.swing.JButton SbSeemore2;
    private javax.swing.JButton SbSeemore3;
    private javax.swing.JButton SbSeemore4;
    private javax.swing.JButton SbSeemore5;
    private javax.swing.JButton SbSeemore6;
    private javax.swing.JButton Sbseemorebtn6;
    private javax.swing.JButton addtocart1;
    private javax.swing.JButton addtocart2;
    private javax.swing.JButton addtocart3;
    private javax.swing.JButton addtocart4;
    private javax.swing.JButton addtocart5;
    private javax.swing.JButton addtocart6;
    private javax.swing.JButton addtocart7;
    private javax.swing.JButton addtocart8;
    private javax.swing.JButton addtocart9;
    private javax.swing.JLabel coffeeNames1;
    private javax.swing.JLabel coffeeNames10;
    private javax.swing.JLabel coffeeNames2;
    private javax.swing.JLabel coffeeNames3;
    private javax.swing.JLabel coffeeNames4;
    private javax.swing.JLabel coffeeNames5;
    private javax.swing.JLabel coffeeNames7;
    private javax.swing.JLabel coffeeNames8;
    private javax.swing.JLabel coffeeNames9;
    private javax.swing.JPanel coffeepanel1;
    private javax.swing.JPanel coffeepanel10;
    private javax.swing.JPanel coffeepanel11;
    private javax.swing.JPanel coffeepanel12;
    private javax.swing.JPanel coffeepanel2;
    private javax.swing.JPanel coffeepanel3;
    private javax.swing.JPanel coffeepanel4;
    private javax.swing.JPanel coffeepanel5;
    private javax.swing.JPanel coffeepanel7;
    private javax.swing.JPanel coffeepanel8;
    private javax.swing.JPanel coffeepanel9;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image10;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel image3;
    private javax.swing.JLabel image5;
    private javax.swing.JLabel image6;
    private javax.swing.JLabel image7;
    private javax.swing.JLabel image8;
    private javax.swing.JLabel image9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Panel panel1;
    private javax.swing.JLabel ratings1;
    private javax.swing.JLabel ratings2;
    private javax.swing.JLabel ratings3;
    private javax.swing.JButton seemore4;
    private javax.swing.JButton seemorebtn5;
    // End of variables declaration//GEN-END:variables
}
